# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# SEO
title: "Julio Noda"
author: "Julio Noda"
description: Arquitecto de Software y Desarrollador Java
url: "https://www.julionoda.com/"
twitter:
  username: julionoda
  card: summary
social:
  links:
    - https://twitter.com/JulioNoda
    - https://www.facebook.com/julio.noda
    - https://www.linkedin.com/in/JulioNoda
    - https://github.com/jnoda
    - https://www.instagram.com/julio.noda

# Collections
collections:
  education:
    output: true
  jobs:
    output: true
  projects:
    output: true

# Defaults
defaults:
  - 
    scope:
      path: ""
      type: "education"
    values:
      layout: "post"
  - 
    scope:
      path: ""
      type: "jobs"
    values:
      layout: "post"
  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
  - 
    scope:
      path: "assets/**.pdf"
    values:
      sitemap: false

# Custom
skin:
  style: "cyan"
  color: "07aaf5"
  type: "light"
social_list:
  linkedin: "https://www.linkedin.com/in/julionoda"
  github: "https://github.com/jnoda"
  twitter: "https://twitter.com/julionoda"
  instagram: "https://www.instagram.com/julio.noda"
  facebook: "https://www.facebook.com/julio.noda"